FROM rocker/verse 
RUN R -e "install.packages(\"tidyverse\")"
RUN R -e "install.packages(\"MASS\")"
RUN R -e "install.packages(\"caret\")"
RUN R -e "install.packages(\"lime\")"
RUN R -e "install.packages(\"dplyr\")"
RUN R -e "install.packages(\"RColorBrewer\")"
RUN R -e "install.packages(\"ggplot2\")"
RUN R -e "install.packages(\"viridis\")"
RUN R -e "install.packages(\"ggridges\")"
RUN R -e "install.packages(\"pROC\")"
RUN R -e "install.packages(\"ranger\")"
RUN R -e "install.packages(\"shiny\")"
RUN R -e "install.packages(\"rmarkdown\")"
RUN R -e "install.packages(\"shinycssloaders\")"
RUN R -e "install.packages(\"methods\")"
RUN R -e "install.packages(\"ROSE\")"
RUN R -e "install.packages(\"vip\")"
RUN Rscript --no-restore --no-save -e "tinytex::tlmgr_install(c(\"wrapfig\",\"ec\",\"ulem\",\"amsmath\",\"capt-of\"))"
RUN Rscript --no-restore --no-save -e "tinytex::tlmgr_install(c(\"hyperref\",\"iftex\",\"pdftexcmds\",\"infwarerr\"))"
RUN Rscript --no-restore --no-save -e "tinytex::tlmgr_install(c(\"kvoptions\",\"epstopdf\",\"epstopdf-pkg\"))"
RUN Rscript --no-restore --no-save -e "tinytex::tlmgr_install(c(\"hanging\",\"grfext\"))"
RUN Rscript --no-restore --no-save -e "tinytex::tlmgr_install(c(\"etoolbox\",\"xcolor\",\"geometry\"))"
